# Form implementation generated from reading ui file 'channel_add.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.lineFirst = QtWidgets.QLineEdit(parent=Dialog)
        self.lineFirst.setGeometry(QtCore.QRect(170, 80, 211, 22))
        self.lineFirst.setObjectName("lineFirst")
        self.lineSecond = QtWidgets.QLineEdit(parent=Dialog)
        self.lineSecond.setGeometry(QtCore.QRect(170, 120, 211, 22))
        self.lineSecond.setObjectName("lineSecond")
        self.lineBandwidth = QtWidgets.QLineEdit(parent=Dialog)
        self.lineBandwidth.setGeometry(QtCore.QRect(170, 160, 211, 22))
        self.lineBandwidth.setObjectName("lineBandwidth")
        self.lineCost = QtWidgets.QLineEdit(parent=Dialog)
        self.lineCost.setGeometry(QtCore.QRect(170, 200, 211, 22))
        self.lineCost.setObjectName("lineCost")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(50, 80, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 122, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(15, 161, 161, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(48, 200, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(100, 20, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.addButton = QtWidgets.QPushButton(parent=Dialog)
        self.addButton.setGeometry(QtCore.QRect(140, 250, 93, 28))
        self.addButton.setObjectName("addButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Узел 1:"))
        self.label_2.setText(_translate("Dialog", "Узел 2:"))
        self.label_3.setText(_translate("Dialog", "Пропускная способность"))
        self.label_4.setText(_translate("Dialog", "Стоимость"))
        self.label_5.setText(_translate("Dialog", "Добавление канала"))
        self.addButton.setText(_translate("Dialog", "Добавить"))
