# Form implementation generated from reading ui file '.\shortest_path.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ShortestPathDialog(object):
    def setupUi(self, ShortestPathDialog):
        ShortestPathDialog.setObjectName("ShortestPathDialog")
        ShortestPathDialog.resize(478, 210)
        self.fromChoice = QtWidgets.QComboBox(parent=ShortestPathDialog)
        self.fromChoice.setGeometry(QtCore.QRect(30, 100, 161, 31))
        self.fromChoice.setObjectName("fromChoice")
        self.toChoice = QtWidgets.QComboBox(parent=ShortestPathDialog)
        self.toChoice.setGeometry(QtCore.QRect(280, 100, 161, 31))
        self.toChoice.setObjectName("toChoice")
        self.label = QtWidgets.QLabel(parent=ShortestPathDialog)
        self.label.setGeometry(QtCore.QRect(80, 70, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=ShortestPathDialog)
        self.label_2.setGeometry(QtCore.QRect(330, 70, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=ShortestPathDialog)
        self.label_3.setGeometry(QtCore.QRect(200, 20, 171, 16))
        self.label_3.setObjectName("label_3")
        self.findButton = QtWidgets.QPushButton(parent=ShortestPathDialog)
        self.findButton.setGeometry(QtCore.QRect(190, 150, 93, 28))
        self.findButton.setObjectName("findButton")

        self.retranslateUi(ShortestPathDialog)
        QtCore.QMetaObject.connectSlotsByName(ShortestPathDialog)

    def retranslateUi(self, ShortestPathDialog):
        _translate = QtCore.QCoreApplication.translate
        ShortestPathDialog.setWindowTitle(_translate("ShortestPathDialog", "Нахождение кратчайшего пути"))
        self.label.setText(_translate("ShortestPathDialog", "Из узла:"))
        self.label_2.setText(_translate("ShortestPathDialog", "В узел:"))
        self.label_3.setText(_translate("ShortestPathDialog", "Укажите узлы"))
        self.findButton.setText(_translate("ShortestPathDialog", "Найти"))
